// Mock data for KIT GEMS
import { Gem, Auction } from './types';

export const gems: Gem[] = [
  {
    id: '1',
    name: 'Ceylon Blue Sapphire',
    type: 'sapphire',
    description: 'A stunning royal blue sapphire from Sri Lanka with exceptional clarity and color saturation.',
    price: 12500,
    carat: 3.2,
    color: 'Royal Blue',
    origin: 'Sri Lanka',
    cut: 'Oval',
    clarity: 'VVS1',
    images: ['/gems/sapphire-1.jpg'],
    certification: 'GIA Certified',
    in_stock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Burmese Pigeon Blood Ruby',
    type: 'ruby',
    description: 'Rare pigeon blood ruby with vivid red color and excellent transparency.',
    price: 28000,
    carat: 2.8,
    color: 'Pigeon Blood Red',
    origin: 'Myanmar',
    cut: 'Cushion',
    clarity: 'VS1',
    images: ['/gems/ruby-1.jpg'],
    certification: 'GIA Certified',
    in_stock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Colombian Emerald',
    type: 'emerald',
    description: 'Vivid green emerald from the legendary Muzo mines of Colombia.',
    price: 18500,
    carat: 4.1,
    color: 'Vivid Green',
    origin: 'Colombia',
    cut: 'Emerald Cut',
    clarity: 'VS2',
    images: ['/gems/emerald-1.jpg'],
    certification: 'GIA Certified',
    in_stock: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Flawless White Diamond',
    type: 'diamond',
    description: 'Internally flawless diamond with exceptional brilliance and fire.',
    price: 45000,
    carat: 2.5,
    color: 'D (Colorless)',
    origin: 'Botswana',
    cut: 'Round Brilliant',
    clarity: 'IF',
    images: ['/gems/diamond-1.jpg'],
    certification: 'GIA Certified',
    in_stock: true,
  },
  {
    id: '5',
    name: 'Pink Sapphire',
    type: 'sapphire',
    description: 'Delicate pink sapphire with excellent color and clarity.',
    price: 8500,
    carat: 2.1,
    color: 'Pink',
    origin: 'Madagascar',
    cut: 'Oval',
    clarity: 'VVS2',
    images: ['/gems/sapphire-2.jpg'],
    in_stock: true,
  },
  {
    id: '6',
    name: 'Smoky Quartz',
    type: 'quartz',
    description: 'Large smoky quartz with beautiful transparency and natural color.',
    price: 850,
    carat: 12.5,
    color: 'Smoky Brown',
    origin: 'Brazil',
    cut: 'Cushion',
    clarity: 'VS1',
    images: ['/gems/quartz-1.jpg'],
    in_stock: true,
  },
];

export const auctions: Auction[] = [
  {
    id: 'a1',
    gem_id: 'a1-gem',
    gem: {
      id: 'a1-gem',
      name: 'Kashmir Sapphire',
      type: 'sapphire',
      description: 'Extremely rare Kashmir sapphire with the legendary velvety blue color.',
      price: 0,
      carat: 5.2,
      color: 'Cornflower Blue',
      origin: 'Kashmir',
      cut: 'Cushion',
      clarity: 'VVS1',
      images: ['/gems/kashmir-sapphire.jpg'],
      certification: 'GIA & Gübelin Certified',
      in_stock: false,
    },
    starting_bid: 50000,
    current_bid: 87500,
    bid_count: 23,
    start_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'live',
    bids: [],
  },
  {
    id: 'a2',
    gem_id: 'a2-gem',
    gem: {
      id: 'a2-gem',
      name: 'Paraíba Tourmaline',
      type: 'other',
      description: 'Vivid neon blue Paraíba tourmaline, one of the rarest gemstones in the world.',
      price: 0,
      carat: 3.8,
      color: 'Neon Blue',
      origin: 'Brazil',
      cut: 'Oval',
      clarity: 'VS1',
      images: ['/gems/paraiba.jpg'],
      certification: 'GIA Certified',
      in_stock: false,
    },
    starting_bid: 35000,
    current_bid: 62000,
    bid_count: 18,
    start_time: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    status: 'live',
    bids: [],
  },
  {
    id: 'a3',
    gem_id: 'a3-gem',
    gem: {
      id: 'a3-gem',
      name: 'Star Ruby',
      type: 'ruby',
      description: 'Rare star ruby exhibiting perfect six-ray asterism.',
      price: 0,
      carat: 6.5,
      color: 'Deep Red',
      origin: 'Myanmar',
      cut: 'Cabochon',
      clarity: 'Translucent',
      images: ['/gems/star-ruby.jpg'],
      certification: 'GIA Certified',
      in_stock: false,
    },
    starting_bid: 15000,
    current_bid: 28500,
    bid_count: 12,
    start_time: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'live',
    bids: [],
  },
];
